### ISSUE TITLE
Need to use escapeDDL for "key"

### ISSUE THREAD

**Issue by cyph84** [db-migrate/db-migrate-base#17]
Mysql treats "key" as a reserved keyword.

[ERROR] Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = '__dbmigrate_schema__'' at line 1

functions _getKV and _deleteKV are the obvious offenders.

**Comment by wzrdtales** [comment]
good catch! will fix this asap
