### ISSUE TITLE
unescaped reference to 'key' field in migration_state table.

### ISSUE THREAD

**Issue by little-monsters** [db-migrate/db-migrate-base#25]
There is an unescaped reference to the `key` field in the `migration_state` table on line 648 of index.js in the `_updateKVC` function definition. This is a syntax error in MySQL and MariaDB because `key` is a reserved keyword. I have confirmed that wrapping it in backticks solves the problem. This can be applied by calling the `escapeDDL` function on it similar to `value` in the same statement. I can submit a pull request if this helps.

**Comment by wzrdtales** [comment]
good catch! thanks for reporting, I published a new version of the mysql driver and the base driver.
